version: '3.9'
services:
  backend:
    container_name: app_backend
    build: ./backend
    ports:
      - 3001:3001
    platform: linux/x86_64
    working_dir: /app-backend
    depends_on:
      postgresql:
        condition: service_healthy
    environment:
      - APP_PORT=3001
      # Os dados abaixo se referem ao container `db`
      # Dica: Relembre aqui da comunicação interna entre containers
    healthcheck:
      test: ["CMD", "lsof", "-t", "-i:3001"] # Caso utilize outra porta interna para o back, altere ela aqui também
      timeout: 10s
      retries: 5
  postgresql:
        image: postgres
        restart: always
        container_name: postgresql
        platform: linux/x86_64
        logging:
          options:
            max-size: 10m
            max-file: "3"
        ports:
          - 5432:5432
        environment:
        - POSTGRES_PASSWORD=123456
        - POSTGRES_USER=postgres
        - POSTGRES_DB=todolist
        healthcheck:
         test: [ "CMD", "pg_isready", "-q", "-d", "postgres", "-U", "postgres" ]
         timeout: 10s
         retries: 5
        cap_add:
        - SYS_NICE # Deve omitir alertas menores